### ISSUE TITLE
In addition to percentage additive, percentage multiplicative stat for every stats only for boss debuff !

### ISSUE THREAD

**Issue by Evilgrill** [fdsatrew3/rpg#116]
### WARNING
**Only for boss debuff ! Giving this to hero will skyrocket stats like Titanbreaker. Actually i have no problem with that but let heroes use additive ones kekw**

### 1) why not flat?
Boss debuff that reduce stats cannot be flat because it will fuck early game and tickle late game.
### 2) why not percentage additive?
Currently, it is percent additive that +/- along with hero item/buff/talent.

If a hero has no self-buff, boss reduces 50% attack speed actually reduces 50% total attack speed.

However, if a hero has 100% attack speed bonus, the problem arises.

They will need to be added together so total % = 100%(innate) +100% -50% = 150%

"The 50%" that boss reduces is only 25% from total attack speed. (200%>150%)

In this case, boss need to reduce 100% attack speed to make it back to 100%.

But reducing 100% attack speed on hero with no self buff with fuck that boi and make him cannot attack.

**Comment by Evilgrill** [comment]
done

**Comment by fdsatrew3** [comment]
Check that shit calculation with negative values
