### ISSUE TITLE
Dark Willow

### ISSUE THREAD

**Issue by fdsatrew3** [fdsatrew3/rpg#93]
--- DARK WILLOW ---

Q - Wisp Companion
Rank 1 - Learn spell - PASSIVE: Whenever you attack an enemy, Wispy (name subject to change) flies to attack it for 50% AGI, then returns to its holder. (it can't attack again until it comes back; doesn't apply modifiers) ACTIVE: Send the wisp to an ally. It will attack from the ally's position instead. Wispy Movement Speed - 600, Cooldown - 15 ; (Wispy is invulnerable and its default position is in your lantern)
Rank 2 - When returning after an attack, the wisp heals its holder for the damage it dealt.
Rank 3 - When you send the wisp to an ally, it grants them 25% primary attribute for 5 seconds.
Rank 4 - You have 1.0 reduced BAT on the attack that sends out Wispy.

W - Flashbang
Rank 1 - Learn spell - Wispy emits a blinding flash of light in a circle, dealing 150% AGI Nature dmg and causing enemies to miss all attacks for 2 seconds. Cooldown - 20
Rank 2 - Flashbang summons an invulnerable shadow behind you for 5 seconds, which has 1 damage, 100% of your attack speed and can apply attack modifiers.
Rank 3 - Targets take 25% more damage over time for 10 seconds.
Rank 4 - Reduces your other ability cooldowns by 4 seconds every time you Flashbang.

E - Grasping Roots
Rank 1 - Learn spell - Roots one enemy in place for 1 second and deals 40% AGI Damage per second for 5 seconds.
Rank 2 - Attacking the affected target has a 20% chance to spread Grasping Vines to a nearby unaffected enemy.
Rank 3 - When Wispy attacks, it will bounce to all enemies affected by Grasping Roots.
Rank 4 - Your Nature damage becomes Nature Earth damage. Increases your Earth damage by 20%.

D - Crown of Death
Rank 1 - Learn spell - For 10s, your attacks apply a stacking Nature DoT to the enemy. Dmg - 2% AGI (max 30 stacks) Duration - 10 Cd - 40
Rank 2 - At the end of the DoT duration, the target explodes for 10% AGI per stack in a 400 AOE.
Rank 3 - During this ability, Wispy's attacks apply the DoT.
Rank 4 - You and Wispy's critical strikes with attacks deal 20% extra damage as Nature over 5 seconds.

F - Wispering Doom
Rank 1 - Learn spell - Launches an army of wisps towards the target location. They latch onto enemy units in their path and detonate with a 1 second delay. They take 175% AGI Nature damage and are stunned for 1 second. Cooldown - 18
Rank 2 - When you take lethal damage, instead Wispy sacrifices itself to save you, detonating in a 500 AoE around you (same damage and stun as ability) and healing you for the damage dealt. Wispy respawns for 20 seconds, during which your Q and R are disabled. 80 second cooldown.
Rank 3 - The detonation reduces enemies' Armor and Nature Resistance by 20% for 4 seconds.
Rank 4 - Wispy enrages and gains 100% Movement Speed for 8 seconds after a wisp dies, during which Wisp Ally and Shadow Vortex deal 50% more damage.

R - Shadow Vortex
Rank 1 - Learn spell - Sends Wispy to rapidly circle in the area, causing a whirlpool of dark energy that deals 30% AGI Nature damage per second. Wispy can't attack while spinning (and Q is disabled). Duration - 5, Radius - 600, Cooldown - 25
Rank 2 - Enemies are continuously pulled towards the center of the vortex.
Rank 3 - Automatically cast Flashbang at the end of Shadow Vortex.
Rank 4 - Every time an affected enemy takes 5 damage instances, they drown and take an extra 200% AGI Nature damage and are silenced for 1 second.

**Comment by MistAssassin69** [comment]
X - Reverse Tether
Rank 1 - Learn ability: Wispy pulls the targeted ally towards itself and gives it 30% Movement speed for 3 seconds. 1k range, 30 cooldown
Rank 2 - Doubles the cast range and heals the target for 200% AGI.
Rank 3 - The ability gains a second charge. (30 seconds charge restore time)
Rank 4 - This ability also creates a protective area around Wispy that gives 50% DR in a 300 AoE for 3 seconds.

X - Nightfall
Rank 1 - Learn ability: Places a curse on all enemies affected by any of your debuffs. They begin taking 200% AGI damage over 20 seconds. After 2 seconds, they will fall asleep and become incapacitated for 5 seconds. Any non-periodic damage will wake the targets up. Cooldown - 40
Rank 2 - Enemies deal 20% less damage for 5 seconds after waking up.
Rank 3 - Sleeping enemies take 75% more damage over time.
Rank 4 - The damage instance that wakes up the targets will critically strike for 500%.

**Comment by fdsatrew3** [comment]
Done.

**Comment by fdsatrew3** [comment]
Done.
